### ISSUE TITLE
Range error 200 - 599

### ISSUE THREAD

**Issue by Noni639** [DogeNetwork/v4#68] opened 2024-05-07 16:27 UTC

**Comment by Noni639** [comment] 2024-05-07 16:28
Uploading RPReplay_Final1715099114.mov…

**Comment by Noni639** [comment] 2024-05-07 16:29
https://github.com/DogeNetwork/v4/assets/161500258/1954012b-c468-4dc4-a091-1f1c77b35a68

**Comment by DerpmanDev** [comment] 2024-05-08 23:20
That is most likely a memory issue, if you are using Vercel, then we cannot do anything about it.

**Comment by CelloKit** [comment] 2024-05-22 12:34
hi!

the error you're receiving means that our server (or the server hosted on vercel) returned a status code (like 200 OK, 404 not found and such) 0, which is not a proper status code, which means that Doge can't handle it.
vercel usually has memory limits. If this is a public link, or people have access to the link, it's possible that you've used up all of the memory usage provided by vercel

if you want to avoid this error, use the FreeDNS deploy method listed in the discord.

**Comment by CelloKit** [comment] 2024-05-22 12:34
if your issue is solved, or we have explained to you thoroughly for you to understand, please close this issue

**Comment by MorroTheCoder** [comment] 2024-05-31 01:44
ive got a simmalar issue ive deployed it with vercel 
https://dogeunlockerv4-qow1h99wn-morrothecoders-projects.vercel.app/ my deployment

**Comment by KDust7** [comment] 2024-05-31 11:28
Look at my comment in the issue you created.

**Comment by KDust7** [comment] 2024-05-31 11:29
To add on to CelloKit, another way to solve the problem is just use a new link

**Closed** 2024-12-05 23:30 UTC
Labels: bug, help wanted
